CFLAGS=-O2 -I. -Iamd -Icolamd -Iminisat -Izlib -DHAVE_CONFIG_H -D_CRT_SECURE_NO_WARNINGS
glpk: glpapi.o glpavl.o glpbfi.o glpbfx.o glpdmp.o glpgmp.o glphbm.o glpiet.o \
glpinv01.o glpinv02.o glpios01.o glpios02.o glpios03.o glpipm.o glpipp01.o \
glpipp02.o glplib01.o glplib02.o glplib03.o glplib04.o glplib05.o glplib06.o \
glplib07.o glplib08.o glplib09.o glplpp01.o glplpp02.o glplpx01.o glplpx02.o \
glplpx03.o glplpx04.o glplpx05.o glplpx06.o glplpx07.o glplpx08.o glplpx09.o \
glplpx10.o glplpx11.o glplpx12.o glplpx13.o glplpx14.o glplpx15.o glplpx16.o \
glplpx17.o glplpx18.o glplpx19.o glpluf01.o glpluf02.o glplux.o glpmat.o \
glpmip01.o glpmip02.o glpmpl01.o glpmpl02.o glpmpl03.o glpmpl04.o glpqmd.o \
glprng.o glpspx01.o glpspx02.o glpssx01.o glpssx02.o glpstr.o glptsp.o
